import { useEffect, useMemo, useRef, useState } from "react";
import { Box, Text, render, useApp, useInput, useWindowSize, type RenderOptions } from "ink";
import type { PlanNode, PlanTask, PlannedDiff } from "../augment/types.js";
import { AugmentTuiController, candidatesForEntry, type PlannedTreeRow, type TuiActionState } from "./controller.js";
import { detailLines, entryName, entryState, entryTouchesNode, frameLayout, theme, type DetailLine, type FrameLayout, type InputMode, type LiveStatus, type RowLiveFlags, type RowView } from "./detail.js";
import { Picker, availableModels, toPickerItems, type PickerItem } from "./setup.js";


const SPINNER_FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];

function PlannedRow(props: { row: PlannedTreeRow; task?: PlanTask; selected: boolean; width: number; view: RowView }) {
  const state = entryState(props.task, props.row, props.view);
  return (
    <Box backgroundColor={props.selected ? theme.selected : undefined}>
      <Text wrap="truncate-end">
        {props.row.branch}
        {state.indicator ? <Text color={state.color}>{state.indicator}</Text> : null}
        {state.indicator ? " " : null}
        <Text
          color={props.row.repositoryOnly ? theme.muted : props.row.entry.kind === "dir" ? theme.accent : theme.text}
          bold={!props.row.repositoryOnly}
        >
          {entryName(props.row.entry)}
        </Text>
        {props.row.folded ? <Text color={theme.muted}> ▸</Text> : null}
        {state.suffix ? (
          <>
            {" "}
            <Text color={theme.muted}>{state.suffix}</Text>
          </>
        ) : null}
      </Text>
    </Box>
  );
}

function DetailView(props: { state: TuiActionState; row?: PlannedTreeRow; offset: number; limit: number; live?: LiveStatus }) {
  const lines = useMemo(() => detailLines(props.state.task, props.row, {
    pendingMarks: props.state.pendingMarks,
    pendingMode: props.state.pendingMode,
    appliedDiffIds: props.state.appliedDiffIds,
    live: props.live,
  }), [props.state.task, props.row, props.state.pendingMarks, props.state.pendingMode, props.state.appliedDiffIds, props.live]);
  const clamped = Math.min(props.offset, Math.max(0, lines.length - props.limit));
  const visible = lines.slice(clamped, clamped + props.limit);
  return (
    <Box flexDirection="column" paddingX={1}>
      {visible.map((line, index) => (
        <Text key={`${clamped + index}:${line.text}`} wrap="wrap" color={line.color} bold={line.bold}>{line.text}</Text>
      ))}
    </Box>
  );
}

function inputTitle(mode: InputMode, target = "repo"): string {
  if (mode === "objective") return "What should change?";
  if (mode === "explanation") return "Explain what repository topic?";
  if (mode === "message") return `${target} · message (empty = rethink)`;
  if (mode === "reopen") return "Reason for reopening selected node";
  if (mode === "stale") return "Changed repository path";
  return "Message";
}

function visibleWindow<T>(items: T[], selected: number, limit: number): T[] {
  if (items.length <= limit) return items;
  const start = Math.max(0, Math.min(items.length - limit, selected - Math.floor(limit / 2)));
  return items.slice(start, start + limit);
}

export function AugmentTui(props: { controller: AugmentTuiController; modelAvailable: boolean; modelLabel?: string }) {
  const { exit } = useApp();
  const windowSize = useWindowSize();
  const [state, setState] = useState<TuiActionState>(() => props.controller.snapshot());
  const [pane, setPane] = useState<"tree" | "detail">("tree");
  const [detailOffset, setDetailOffset] = useState(0);
  const [spinnerFrame, setSpinnerFrame] = useState(0);
  const [mode, setMode] = useState<InputMode>("idle");
  const [modelPicker, setModelPicker] = useState<
    | { kind: "role" }
    | { kind: "model"; role: "model" | "draftModel" | "challengeModel"; items: PickerItem[]; note?: string }
    | { kind: "model"; role: "model" | "draftModel" | "challengeModel"; loading: true }
    | undefined
  >(undefined);
  const [inputValue, setInputValue] = useState("");
  const autoGenerated = useRef(new Set<string>());
  const autoRetried = useRef(new Set<string>());
  const initialSnapshot = state;

  useEffect(() => {
    if (!state.busy) return;
    const timer = setInterval(() => setSpinnerFrame((current) => current + 1), 120);
    return () => clearInterval(timer);
  }, [state.busy]);

  const sync = () => {
    setState(props.controller.snapshot());
  };

  // External mutations (an agent driving this task over the TUI's socket)
  // repaint the app as they land; user actions sync through `run`/`sync`.
  useEffect(() => {
    const unsubscribe = props.controller.subscribe(() => setState(props.controller.snapshot()));
    return unsubscribe;
  }, [props.controller]);

  const run = (action: Promise<void>) => {
    // Controller dispatch marks itself busy synchronously before its first await.
    sync();
    void action.then(sync, (error: unknown) => {
      setState((current) => ({
        ...current,
        busy: false,
        operation: undefined,
        error: error instanceof Error ? error.message : String(error),
      }));
    });
  };

  useEffect(() => {
    const task = initialSnapshot.task;
    const root = task?.nodes[task.rootNodeId];
    if (!props.modelAvailable || !task || task.mode !== "change" || !root || root.status !== "unresolved" || root.candidateIds.length || initialSnapshot.busy || autoGenerated.current.has(task.id)) return;
    autoGenerated.current.add(task.id);
    // The first generation is the app's front door: one transient model
    // failure must never leave a silent, empty task. Retry once and say so.
    run(props.controller.crystallize().then(() => {
      const snapshot = props.controller.snapshot();
      const stalled = snapshot.task?.nodes[snapshot.task.rootNodeId!];
      if (!snapshot.task || snapshot.busy || stalled?.status !== "unresolved" || stalled.candidateIds.length || autoRetried.current.has(snapshot.task.id)) return;
      autoRetried.current.add(snapshot.task.id);
      setState((current) => ({ ...current, message: "First generation attempt failed — retrying once… press [D] anytime to retry manually." }));
      run(props.controller.crystallize());
    }));
  }, [props.controller, props.modelAvailable, initialSnapshot]);

  useEffect(() => {
    setDetailOffset(0);
  }, [state.selectedRowId]);

  const beginInput = (next: InputMode) => {
    setMode(next);
    setInputValue("");
  };

  const cancelInput = () => {
    setMode("idle");
    setInputValue("");
  };

  const submit = (submittedValue = inputValue) => {
    const value = submittedValue;
    const activeMode = mode;
    cancelInput();
    if (activeMode === "objective") run(props.controller.start(value));
    else if (activeMode === "explanation") run(props.controller.explain(value));
    else if (activeMode === "message") run(props.controller.rethink(value));
    else if (activeMode === "reopen") run(props.controller.reopen(value));
    else if (activeMode === "stale") run(props.controller.markStale(value));
  };

  useInput((input, key) => {
    if (modelPicker) return;
    if (mode !== "idle") {
      const submitMarker = key.return || key.tab || input.includes("\r") || input.includes("\n") || input.includes("\t");
      if (submitMarker) {
        const pastedPrefix = input.split(/[\r\n\t]/)[0] ?? "";
        const value = inputValue + pastedPrefix;
        setInputValue(value);
        submit(value);
      }
      else if (key.escape) cancelInput();
      else if (key.backspace) setInputValue((current) => current.slice(0, -1));
      else if (input && !key.ctrl && !key.meta) setInputValue((current) => current + input);
      return;
    }

    if (key.escape && state.busy) {
      props.controller.cancel();
      setState((current) => ({ ...current, message: "Cancelling the running operation…" }));
      return;
    }
    if (pane === "detail" && (key.upArrow || input === "k")) {
      setDetailOffset((current) => Math.max(0, current - 1));
      return;
    }
    if (pane === "detail" && (key.downArrow || input === "j")) {
      setDetailOffset((current) => current + 1);
      return;
    }
    if (key.upArrow || input === "k") {
      props.controller.move(-1);
      sync();
      return;
    }
    if (key.downArrow || input === "j") {
      props.controller.move(1);
      sync();
      return;
    }
    if (key.tab || key.rightArrow) {
      setPane((current) => (current === "tree" ? "detail" : "tree"));
      return;
    }
    if (key.leftArrow) {
      setPane("tree");
      return;
    }
    if (key.return || input === "\r" || input === "\n") {
      if (!state.task) {
        props.controller.report("No task is active. Press [N] for a change or [E] for an explanation.");
        return;
      }
      beginInput("message");
      return;
    }

    const command = input.toLowerCase();
    const selectedEntry = props.controller.selectedRow()?.entry;
    const choices = candidatesForEntry(props.controller.snapshot().task, selectedEntry).filter((candidate) => candidate.status === "possible");
    const numericChoice = Number(command);
    if (Number.isInteger(numericChoice) && numericChoice >= 1 && numericChoice <= choices.length) {
      run(props.controller.selectCandidate(choices[numericChoice - 1]!.id));
      return;
    }

    if (command === "q") {
      props.controller.cancel();
      exit();
    }
    else if (command === "n") beginInput("objective");
    else if (command === "e") beginInput("explanation");
    else if (command === "d") run(props.controller.develop());
    else if (command === "a") run(props.controller.applySelected());
    else if (command === "c") run(props.controller.commitApplied());
    else if (command === "l") run(props.controller.toggleRestriction("lock"));
    else if (command === "w") run(props.controller.toggleRestriction("allow"));
    else if (command === "f") {
      props.controller.toggleFold();
      sync();
    }
    else if (command === "h") {
      props.controller.toggleRelatedOnly();
      sync();
    }
    else if (command === "m") {
      if (props.controller.runtimeAgent()) setModelPicker({ kind: "role" });
      else setState((current) => ({ ...current, error: "No model runtime is active." }));
    }
    else if (command === "o") beginInput("reopen");
    else if (command === "s") beginInput("stale");
  });

  const selectedIndex = state.rows.findIndex((row) => row.id === state.selectedRowId);
  const layout = frameLayout(windowSize.rows, mode);
  const treeRows = visibleWindow(state.rows, selectedIndex, layout.treeRows);
  const treeWidth = Math.max(30, Math.floor(windowSize.columns * 0.42) - 6);
  const detailLimit = layout.detailRows;
  const spinner = SPINNER_FRAMES[spinnerFrame % SPINNER_FRAMES.length]!;
  const liveStatus: LiveStatus | undefined = state.active || state.failed
    ? { spinner, active: state.active, failed: state.failed }
    : undefined;
  const rootStatus = state.task?.nodes[state.task.rootNodeId]?.status;
  const status = state.busy
    ? "BUSY"
    : state.task?.mode === "explanation"
      ? Object.keys(state.task.explanations).length ? "EXPLAINED" : "EXPLAINING"
      : rootStatus ? rootStatus.toUpperCase() : "IDLE";
  const selectedRow = state.rows.find((row) => row.id === state.selectedRowId);
  const statusMessage = state.busy ? `${state.operation ?? "Working"}...` : state.error ?? state.message;

  return (
    <Box flexDirection="column" height={layout.frameRows} width={windowSize.columns} padding={1}>
      <Box gap={2} flexShrink={0}>
        <Text color={theme.primary} bold>NEOLIT</Text>
        <Text color={state.error ? theme.error : status === "IDLE" ? theme.muted : theme.success}>[{status}]</Text>
        <Text color={theme.secondary}>[{state.task?.mode === "explanation" ? "EXPLANATION" : "PLANNED CHANGE"}]</Text>
        {(state.task?.lockedPaths.length ?? 0) > 0 || state.pendingMarks.length > 0 ? (
          <Text color={(state.task?.restrictionMode ?? state.pendingMode) === "lock" ? theme.error : theme.accent}>
            [{(state.task?.restrictionMode ?? state.pendingMode) === "lock" ? "LOCK" : "ALLOW"} {state.task?.lockedPaths.length ?? state.pendingMarks.length}]
          </Text>
        ) : null}
        {state.relatedOnly ? <Text color={theme.secondary}>[RELATED]</Text> : null}
        {state.task ? (
          <Text color={theme.muted}>r{state.task.revision} · {state.task.basisRevision.slice(0, 12)}</Text>
        ) : null}
        {state.socketPath ? (
          <Text color={theme.muted}>⎇ agents: {state.socketPath}</Text>
        ) : null}
        <Box flexGrow={1} />
        <Text color={props.modelAvailable ? theme.success : theme.warning}>{props.modelAvailable ? props.modelLabel ?? "OPENCODE" : "NO MODEL"}</Text>
      </Box>

      {modelPicker ? (
        <Box flexGrow={1} minHeight={0} flexDirection="column">
          {modelPicker.kind === "role" ? (
            <Picker
              title="Switch which model?"
              items={[
                { id: "model", label: "default" },
                { id: "draftModel", label: "draft" },
                { id: "challengeModel", label: "challenge" },
              ]}
              onDone={(id) => {
                if (!id) return setModelPicker(undefined);
                const role = id as "model" | "draftModel" | "challengeModel";
                setModelPicker({ kind: "model", role, loading: true });
                const agent = props.controller.runtimeAgent()!;
                void availableModels(agent.backendId, agent.command).then(({ models, source }) => {
                  setModelPicker({ kind: "model", role, items: toPickerItems(models), note: models.length ? source : `${source}` });
                });
              }}
            />
          ) : "loading" in modelPicker ? (
            <Picker title="Loading models…" items={[]} onDone={() => setModelPicker(undefined)} />
          ) : (
            <Picker
              title={`${modelPicker.role === "model" ? "default" : modelPicker.role === "draftModel" ? "draft" : "challenge"} model`}
              note={modelPicker.note}
              items={modelPicker.items}
              onDone={(id) => {
                if (id) props.controller.configureModels({ [modelPicker.role]: id });
                setModelPicker(undefined);
              }}
            />
          )}
        </Box>
      ) : (
      <Box flexGrow={1} minHeight={0} gap={1}>
        <Box width="42%" flexShrink={0} borderStyle="round" borderColor={pane === "tree" ? theme.borderActive : theme.border} flexDirection="column" overflow="hidden" paddingX={1}>
          <Text color={pane === "tree" ? theme.primary : theme.muted} bold>FILES</Text>
          {treeRows.length === 0 ? (
            <Text color={theme.muted}>No plan yet. Press [N].</Text>
          ) : treeRows.map((row) => {
            const activeRow = entryTouchesNode(row.entry, state.active?.nodeId);
            const failedRow = entryTouchesNode(row.entry, state.failed?.nodeId);
            return (
              <PlannedRow
                key={row.id}
                row={row}
                task={state.task}
                selected={state.selectedRowId === row.id}
                width={treeWidth}
                view={{
                  pendingMarks: state.pendingMarks,
                  pendingMode: state.pendingMode,
                  appliedDiffIds: state.appliedDiffIds,
                  live: activeRow || failedRow ? { active: activeRow, failed: failedRow, spinner, operation: state.active?.operation } : undefined,
                }}
              />
            );
          })}
        </Box>

        <Box flexGrow={1} minWidth={30} borderStyle="round" borderColor={pane === "detail" ? theme.borderActive : theme.border} flexDirection="column" overflow="hidden" paddingTop={0}>
          <DetailView state={state} row={selectedRow} offset={detailOffset} limit={detailLimit} live={liveStatus} />
        </Box>
      </Box>
      )}

      <Box paddingTop={1} flexShrink={0}>
        <Text wrap="truncate-end">
          <Text color={theme.primary} bold>[Enter]</Text>
          <Text color={theme.primary}> prompt/regenerate · </Text>
          <Text color={theme.primary} bold>[1-7]</Text>
          <Text color={theme.primary}> choose approach · </Text>
          <Text color={theme.primary} bold>[D]</Text>
          <Text color={theme.primary}> develop · </Text>
          <Text color={theme.primary} bold>[A]</Text>
          <Text color={theme.primary}> apply · </Text>
          <Text color={theme.primary} bold>[C]</Text>
          <Text color={theme.primary}> commit · </Text>
          <Text color={theme.primary} bold>[L]</Text>
          <Text color={theme.primary}> lock · </Text>
          <Text color={theme.primary} bold>[W]</Text>
          <Text color={theme.primary}> allow · </Text>
          <Text color={theme.primary} bold>[M]</Text>
          <Text color={theme.primary}> models · </Text>
          <Text color={theme.primary} bold>[E]</Text>
          <Text color={theme.primary}> explain · </Text>
          <Text color={theme.primary} bold>[N]</Text>
          <Text color={theme.primary}> new · </Text>
          <Text color={theme.muted} bold>[F]</Text>
          <Text color={theme.muted}> fold · </Text>
          <Text color={theme.muted} bold>[H]</Text>
          <Text color={theme.muted}> related · </Text>
          <Text color={theme.muted} bold>[Tab]</Text>
          <Text color={theme.muted}> pane · </Text>
          <Text color={theme.muted} bold>[Q]</Text>
          <Text color={theme.muted}> quit</Text>
        </Text>
      </Box>

      {mode === "idle" ? (
        <Box borderStyle="round" borderColor={state.error ? theme.error : state.busy ? theme.warning : theme.border} flexShrink={0} paddingX={1}>
          <Text wrap="wrap" color={state.error ? theme.error : state.busy ? theme.warning : theme.muted}>
            {state.busy ? `${spinner} ${state.operation ?? "Working"}…` : state.error ? state.error.split(/\r?\n/)[0] : statusMessage}
          </Text>
        </Box>
      ) : (
        <Box borderStyle="round" borderColor={theme.borderActive} paddingX={1} flexShrink={0}>
          <Text color={theme.primary} bold>{inputTitle(mode, selectedRow?.entry.path && selectedRow.entry.path !== "." ? selectedRow.entry.path : "repo")} › </Text>
          <Text>{inputValue}<Text inverse> </Text>{inputValue ? "" : inputTitle(mode, selectedRow?.entry.path && selectedRow.entry.path !== "." ? selectedRow.entry.path : "repo")}</Text>
        </Box>
      )}
    </Box>
  );
}

/**
 * Renderer options for the plan TUI. `incrementalRendering` makes Ink rewrite
 * only the lines whose content changed instead of erasing the previous frame
 * and rewriting it whole, so a keypress repaint no longer flashes.
 * `alternateScreen` keeps the plan in a dedicated terminal buffer.
 */
export function tuiRenderOptions(): RenderOptions {
  return {
    alternateScreen: true,
    incrementalRendering: true,
  };
}

export async function runAugmentTui(controller: AugmentTuiController, modelAvailable: boolean, modelLabel?: string): Promise<void> {
  const instance = render(<AugmentTui controller={controller} modelAvailable={modelAvailable} modelLabel={modelLabel} />, tuiRenderOptions());
  await instance.waitUntilExit();
}

export type { PlanTask };
